### ISSUE TITLE
Blatant copy of https://github.com/nachoaIvarez/flexbox-react

### ISSUE THREAD

**Issue by nachoaIvarez** [nantaphop/fbox#1]
Wtf is this man? This is a blatant copy of https://github.com/nachoaIvarez/flexbox-react, which I’ve been building and maintaining for over an year. You copied code and even readme structure man wtf!

**Comment by nantaphop** [comment]
Nonsense man, I didn't copy your code. this is just an easy utility component that easy enough to write in a couple hours.

I already try your library but it didn't catch me according to how I have to type prop value like justifyContent="center".

This is an open source world. We share the same problem that flexbox have a lot of boilerplate code. Then, your solution didn't catch me. How on earth I can't write up another solution that solve the same problem?

About README.md, It really common that readme should contain information installation example usage and etc. How do you say I have to copy your readme structure?.

I already publish some android's library 2 years ago which have readme structure similar to this repo. Did I have time travel or something like that to copy just your readme structure 2 years ago?

https://github.com/nantaphop/HoverTouchView
https://github.com/nantaphop/FluentView
